services:
  sidating-app-db-2:
    image: postgres:17.5-alpine
    ports:
      - '35002:5432'
    restart: 'no'
    environment:
      - POSTGRES_USER=sidatingapp-dev-2
      - POSTGRES_PASSWORD=CLI-825.2025X
      - POSTGRES_DB=sidatingapp-dev-2
    volumes:
      - sidating-app-db-2:/var/lib/postgresql/data
volumes:
  sidating-app-db-2:
    driver: local