spring.application.name=sidating-app-be
spring.mvc.hiddenmethod.filter.enabled=true

spring.datasource.url=jdbc:postgresql://localhost:35001/sidatingapp-dev
spring.datasource.username=sidatingapp-dev
spring.datasource.password=CLI-825.2025X

spring.jpa.hibernate.ddl-auto=create-drop