spring.application.name=sidating-app-be
spring.mvc.hiddenmethod.filter.enabled=true

# Active Profile Configuration
spring.profiles.active=dev

# Default JPA Configuration
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true