server:
  port: 8081
spring:
  application:
    name: sidating-app-be
  
  mvc:
    hiddenmethod:
      filter:
        enabled: true

  profiles:
    active: dev

jpa:
  hibernate:
    ddl-auto: create-drop
  show-sql: true